### ISSUE TITLE
[Tracking Issue] Wing SDK tests

### ISSUE THREAD

**Issue by tsuf239** [winglang/wing#2326]
### Feature Spec

add tests to the following resources:

## Bucket

- [x] on_upload #2452
- [x] on_delete #2452
- [x] on_update #2452
- [x] on_event #2452
- [x] on_event BucketEventType.CREATE #2452
- [x] on_event BucketEventType.DELETE #2452
- [x] on_event BucketEventType.UPDATE #2452
- [x] #2454
- [x] #2457
- [x] #2456
- [x] #2458
- [x] exists #2549 
- [x] try_get #2520
- [x] try_delete #2520
- [x] addObject #2727
- [x] list #2727
- [x] delete #2727
- [x] #2462
- [x] #2461
- [x] #2460

// not implemented yet
- [ ] metadata
- [ ] rename
- [ ] copy
- [ ] signed_url
- [ ] ObjectMetadata.size
- [ ] ObjectMetadata.last_modified
- [ ] ObjectMetadata.content_type

## Queue
- [x] QueueProps.timeout #1979 
- [x] timeout  #1979
- [x] add_consumer  #1979
- [x] approx_size  #1979
- [x] push  #1979
- [x] pop  #1979
- [x] purge  #1979

## Function
- [x] FunctionProps.duration  #1981
- [x] FunctionProps.memory #2328 
- [x] FunctionProps.env  #2328 
- [x] timeout  #1981
- [x] memory  #2328 
- [x] add_environment  #2328 
- [x] invoke #1981 

// not implemented yet
- [ ] invoke_async  #2328 
- [ ] concurrency  #2328 
- [ ] FunctionProps.concurrency  #2328 

## Counter
- [x] CounterProps.initial #1978 
- [x] inc #1978 
- [x] dec #1978 
- [x] peek #1978 
- [x] reset #1978 

## Topic
- [x] on_message #2327
- [x] publish #2327 

## Schedule
- [x] from_cron #2523
- [x] from_rate #2523
- [x] on_tick #2523

## Website
- [x] WebsiteProps.path #2784
- [x] path #2784
- [x] URL #2784

// not implemented yet
- [ ] WebsiteProps.domain

## Api
- [x] options #2731
- [x] head #2731
- [x] connect #2731
- [x] HttpMethod.CONNECT #2731
- [x] HttpMethod.OPTIONS #2731
- [x] HttpMethod.HEAD #2731
- [x] ApiResponse.headers #2731
- [x] URL https://github.com/winglang/wing/pull/2826
- [x] get https://github.com/winglang/wing/pull/2826
- [x] post https://github.com/winglang/wing/pull/2826
- [x] put https://github.com/winglang/wing/pull/2826
- [x] delete https://github.com/winglang/wing/pull/2826
- [x]  patch https://github.com/winglang/wing/pull/2826
- [x] ApiRequest.method https://github.com/winglang/wing/pull/2826
- [x] ApiRequest.path https://github.com/winglang/wing/pull/2826
- [x] ApiRequest.query https://github.com/winglang/wing/pull/2826
- [x] ApiRequest.vars https://github.com/winglang/wing/pull/2826
- [x] ApiRequest.body https://github.com/winglang/wing/pull/2826
- [x] ApiRequest.headers https://github.com/winglang/wing/pull/2826
- [x] ApiResponse.status https://github.com/winglang/wing/pull/2826
- [x] ApiResponse.body https://github.com/winglang/wing/pull/2826
- [x] HttpMethod.GET https://github.com/winglang/wing/pull/2826
- [x] HttpMethod.POST https://github.com/winglang/wing/pull/2826
- [x] HttpMethod.PUT https://github.com/winglang/wing/pull/2826
- [x] HttpMethod.DELETE https://github.com/winglang/wing/pull/2826
- [x] HttpMethod.PATCH https://github.com/winglang/wing/pull/2826

// not implemented yet
- [ ] ApiProps.cors
- [ ] ApiCorsProps.origin
- [ ] ApiCorsProps.methods
- [ ] ApiCorsProps.headers
- [ ] ApiCorsProps.allow_credentials
- [ ] request
- [ ] cors
- [ ] any

### Use Cases

testing, education

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
