### ISSUE TITLE
sdk test spec github action improvements

### ISSUE THREAD

**Issue by tsuf239** [winglang/wing#2689]
### Feature Spec

- [x] Report failures and notify the on-call member
- [x] Run right before releasing a version/ instead of every day
- [ ] ~Add a flag to run it when placing a PR (similar to pr/e2e-full label)~
- [x] adding a flag to disable cleaning the resources + supply the temp dir path to the user.  #2884
- [ ] Randomize resources prefix (root id), by default (and a flag to keep it steady).  #3723 
This way the names of the resources will be randomized and we won't be dependent on cleaning them up before running a test. 
- [ ] Run tests in parallel on a few machines  #3723 
- [ ] Update SDK workflow to run on a few machines #3726 
- [ ] ~Condition the run on the latest changes location (do not run when console, or docs changes)~

moved point 3 and 8 to https://github.com/winglang/wing/issues/3727.

### Use Cases

testing

### Component

SDK

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by monadabot** [comment]
Congrats! :rocket: This was released in [Wing 0.24.90](https://github.com/winglang/wing/releases/tag/v0.24.90).
