### ISSUE TITLE
[Tracking Issue] VSCode extension auto completion

### ISSUE THREAD

**Issue by staycoolcall911** [winglang/wing#2690]
@ekeren worked on this list before and it's about time we track what we have and what we're still missing.

The following scopes are where we'd like to see auto complete supported in the Wing VSCode extension. 
![image](https://github.com/winglang/wing/assets/106860404/482ebc57-4b1c-4bee-bce9-83dbb7038381)

## P1
- [ ] Completion after let
- [ ] Completion after if

## P2
- [ ] Completion inside for declaration - iterator related expressions
- [ ] Completion on class declaration after name (extends/implements)

## P3
- [ ] Completion after bring
- [ ] Completion inside function declaration
- [ ] Completion inside function declaration after colon
- [ ] Completion at top of the file
- [ ] Completion inside preflight function
- [ ] Completion inside inflight function
- [ ] Completion on variable declaration
- [ ] Completion inside for declaration
- [ ] Completion inside while declaration
- [ ] Completion inside while declaration - iterator related expressions
- [ ] Completion on class members area
- [ ] Completion on class init
- [ ] Completion on class method
- [ ] Completion on class inflight init
- [ ] Completion on class inflight method
- [ ] Completion after class init
- [ ] Completion after as
- [ ] Completion after if block (elif/else)
- [ ] Completion after elif
- [ ] Completion after elif block
- [ ] Completion after else block

**Comment by staycoolcall911** [comment]
The code I used in order to see where completion works (it doesn't 😄):
```ts
bring cloud;

let f1 = (s: str): str => {

};

let f2 = (s: str): str => {

};

let a: Array<str> = Array<str> [];

for i in 0..10 {

}

let words = ["hello", "world"];
for word in words {

}

while true {

}

class R {
  a: str;

  init(a: str) {
    this.a = a;
  }

  m1(title: str): str {
    return title + this.a;
  }

  inflight init() {

  }

  inflight m2(title: str): str {
    return title + this.a;
  }
}

class RR extends R {

}

let rr = new RR() as "something";

if 1 == 2 {

} elif 2 == 3 {

} else {

}
```

**Comment by staycoolcall911** [comment]
Updated the supported completions on P3 list in the issue description
