### ISSUE TITLE
[Tracking Issue] Tests for `std` APIs

### ISSUE THREAD

**Issue by eladb** [winglang/wing#2785]
The PR https://github.com/winglang/wing/pull/2783 introduces placeholders for tests for all `std` types under `sdk_tests`.

- [x] #2953 
- [x] #2956
- [x] #2962
- [x] #2956
- [x] json std tests
- [x] #4363
- [x] number std tests
- [x] #4229
- [x] #4372
- [x] string std tests

**Comment by revitalbarletz** [comment]
Set tests last by @WeepingClown13!

**Comment by monadabot** [comment]
Congrats! :rocket: This was released in [Wing 0.35.8](https://github.com/winglang/wing/releases/tag/v0.35.8).
