### ISSUE TITLE
[Tracking issue] Docsite improvements

### ISSUE THREAD

**Issue by Chriscbr** [winglang/wing#2843]
## Use case

Happy docs make for happy developers

## Tasks

- [ ] Organization
  - [x] Update title & description metadata of top pages for SEO (@dannac2 has details) #3164 
  - [x] https://github.com/winglang/wing/issues/3130
  - [x] Move contributing to new tab
- [ ] Content
  - [x] Concept docs - Preflight and Inflight #2022 
  - [x] Concept docs - Application tree  [3163](https://github.com/winglang/wing/issues/3163)
  - [x] Concept docs - Testing (https://github.com/winglang/wing/issues/2192)
  - [x] Wing Console
    - [x] https://github.com/winglang/wing/issues/1185
    - [x] https://github.com/winglang/wing/issues/2558
  - [ ] Wing Cloud Library
    - [x] https://github.com/winglang/wing/issues/2652
    - [x] https://github.com/winglang/wing/issues/2655
    - [x] https://github.com/winglang/wing/issues/2656
    - [x] https://github.com/winglang/wing/issues/2657
    - [x] https://github.com/winglang/wing/issues/2662
  - [x] https://github.com/winglang/wing/issues/2449
  - [x] https://github.com/winglang/wing/issues/2565
  - [ ] https://github.com/winglang/wing/issues/3034
- [ ] API reference(s)
  - [ ] https://github.com/winglang/wing/issues/2710
  - [x] Rename types e.g. ImmutableArray => Array
  - [x] Resources should show both preflight methods and inflight methods
  - [x] Break up docs into multiple pages
  - [ ] Language spec should link to relevant types in API reference
  - [ ] Hide internal types ("T1")
  - [ ] Special-case docs for `Util` classes to show e.g. `util.sleep()` instead of `util.Util.sleep()`
  - [ ] Show namespaces in headings, e.g. cloud.Bucket instead of Bucket
  - [ ] Inline fields of BucketProps when showing the parameters of Bucket's constructor, instead of `props: BucketProps`
  - [ ] Show "@return" docstrings
  - [x] Show redis docs 
  - [x] Dedicated markdown files for ALL sdk modules (http, util, etc.)

**Comment by ekeren** [comment]
should https://docs.winglang.io/core-concepts/simulator actually be the console? 

(At the moment, the simulator, is more of an implementation detail and should be part of contributing docs)

**Comment by Chriscbr** [comment]
Yep I think that makes sense

**Comment by ekeren** [comment]
notes from discussion with @Chriscbr and @ekeren: 
- [ ] move simulator to tools 
- [ ] decide about https://www.winglang.io/docs/language-guide/reference
- [ ] fix broken links from Resources to API reference
![Image](https://github.com/winglang/wing/assets/1727147/fc613558-77e0-48c7-8e5c-76198786a197)
- [ ] p2 standard types for Arrays
