### ISSUE TITLE
Align headers on all sites

### ISSUE THREAD

**Issue by dannac2** [winglang/wing#2983]
## Winglang.io
![Image](https://github.com/winglang/wing/assets/1727147/90e3fc6a-a917-4793-bda8-758bd1dae4d7)

## Docs

![Image](https://github.com/winglang/wing/assets/1727147/6b6b5968-6d47-4a7f-93f2-33a8e19e690b)

## Playground

![Image](https://github.com/winglang/wing/assets/1727147/93fbe7bb-9e6a-4307-aafa-09f1e460e03f)

```[tasklist]
### Tasks
- [x] github stars should be in K
- [x] it should look similar both in dark and light mode
- [x] make sure we use the same favicon
- [x] install should apear on learn.winglang.io
```

**Comment by ekeren** [comment]
@polamoros  , I've added a favicon task



![Image](https://github.com/winglang/wing/assets/1727147/39958a06-a870-4191-bd48-a3c9cd9d8cb8)

**Comment by ekeren** [comment]
@polamoros , notice update in the definition

**Comment by polamoros** [comment]
We should change the fav icon of the winglang.io site.

I added an issue for this:
https://github.com/winglang/marketing/issues/251

**Comment by ainvoner** [comment]
@polamoros @ekeren what about adding `contributing` to the winglang.io header as well?

**Comment by ekeren** [comment]
@polamoros already added it to the playground 
https://github.com/winglang/playground/pull/199#pullrequestreview-1509537774

And to the docs:
https://github.com/winglang/playground/pull/199#pullrequestreview-1509537774

**Comment by ekeren** [comment]
I do think that the header is way to noise 
![Screenshot 2023-07-02 at 13 53 24](https://github.com/winglang/wing/assets/1727147/38fd3537-b2de-4fa2-bdd3-8e866f68ba72)



@eladb , @dannac2 
![Screenshot 2023-07-02 at 13 53 48](https://github.com/winglang/wing/assets/1727147/1114b08d-119d-47dc-a44c-07a65dd785a9)
