### ISSUE TITLE
events naming conventions

### ISSUE THREAD

**Issue by ekeren** [winglang/wing#3321]
Status | Source | Object | Action | Event Name | Properties | Comment | Original event
-- | -- | -- | -- | -- | -- | -- | -- 
done | console | session | start | console_session_start |   | store a session id
done | console | \<resource\> (counter/bucket/queue) | interact | console_resource_interact | resource:\<resource_name\>,action:\<action_name\> | **duplicate**
done | console | bucket | list | console_bucket_list | prefix: files_retrieved:12 |  
done | console | bucket | put | console_bucket_put | key:file.txt, success:true/false |  
done | console | counter | inc | console_counter_inc |   |  
done  | play | page | block | play_page_block |   |  | play: blocked for device
NO | play | page | ready | play_page_ready |   | |  play: state: Ready
done | play | resource | interact | play_resource_interact | resource:\<\>,action:\<\> | **duplicate**
done | play | bucket | list | play_bucket_list | prefix: files_retrieved:12 |  
done | play | startup | ready | play_startup_ready |   |  
done | play | containers | init | play_containers_init |   |  
done | play | dependency | install | play_dependency_install |   |  
done | play | console | init | play_console_init |   |  
done  | learn:\<tour-name\>  | resource | interact | learn:\<tour-name\>_resource_interact | resource:\<\>,action:\<\> | **duplicate**
done | learn:\<tour-name\> | page | block | learn_page_block |   |  | tour: Introduction: blocked for device
done | learn:\<tour-name\> | step:\<num\> | init | learn:\<tour-name>_step:\<num\>_init |   |  |  tour: Bucket: step: 1: changed
NO | cli | tfaws | compile | cli_tfaws_compile |   |  
NO | cli | sim | test | cli_sim_test |   |  
NO | cli | nil | doc | cli_nil_doc |   |  
NO | cli | nil | help | cli_nil_help |   |  
NO | www | page | view | web_page_view |   |  
  |   |   |   |   |  
  |   |   |   |   |  

```[tasklist]
### Tasks
- [x] implement for learn
- [x] implement for console
- [x] implement for web
- [x] implement for cli
- [x] implement for play
```

**Comment by ainvoner** [comment]
@ekeren regarding the properties required for each event.
this is the data I can get from each trace:
```js
 {
    message: trace?.data?.message || '',
    status: trace?.data?.status || 'unknown',
    result: trace?.data?.result || 'unknown',
 }
 ```
 I don't see a reason to parse and analyze it for each resource in the client.
 so bucket list analytics event would look like:
 ```js
 {
   event: "play_bucket_list",
   properties: {
     message: "List (prefix=null).",
     result: "[\"console-demo-1 copy 2.png\",\"console-logs-3.png\"]",
     status: "success" 
   }
}
```

**Comment by ekeren** [comment]
I am fine with that, but 
`  result: "[\"console-demo-1 copy 2.png\",\"console-logs-3.png\"]",`

We will reach limits on the size of the value, so just make sure you trim a string so it will  not be > 1024

**Comment by ainvoner** [comment]
as discussed, adding a sessionId property to each tracked event:
```js
{
 event: "something",
 properties: {
  ...,
  sessionId
 }
}
```

**Comment by ekeren** [comment]
`session_id`

Notice that we are snake_case and also this is Amplitude expected  
also, the value of session_id should be `Date.now()` (a number value)

**Comment by ekeren** [comment]
Actually, lets put sessionId here:
```
{
 event: "something",
 properties: {
  ...,

 },
 "integrations": {
    "Actions Amplitude": {
      "session_id": 1689073366708
    }
  },
}
```
So it will work seamlessly with amplitude

**Comment by ekeren** [comment]
## Issues seen:
### Console
- [ ] not seeing any events

### Learn
- [ ] event names should be lower case. (examples: `learn:Introduction_resource_interact`, `learn:Bucket_Bucket_List`)
- [ ] learn has events with `learn_` prefix instead of only having events with `learn:<tour name>`. (examples:  `learn_startup_ready`, `learn_resource_interact` should be `learn:introduction_startup_ready`, `learn:bucketplal_resource_interact`

### Play
- [ ] notice missing events and the following error (it could be a root cause of other issues)



![Image](https://github.com/winglang/wing/assets/1727147/fbb8232e-44f1-40f2-aa27-ef0d5175337a)

![Image](https://github.com/winglang/wing/assets/1727147/b3898a45-c9f7-4a4b-aded-57314ab6b2fb)

**Comment by ekeren** [comment]
fixed null reference in https://github.com/winglang/playground/pull/258

**Comment by ainvoner** [comment]
fix event name: https://github.com/winglang/playground/pull/259

**Comment by ainvoner** [comment]
fix for console segment events: https://github.com/winglang/wing/pull/3377
