### ISSUE TITLE
Tracking issue- Cloud coverage project

### ISSUE THREAD

**Issue by tsuf239** [winglang/wing#4505]
### Feature Spec

- [ ] Normalize "unsupported yet" errors- in order to be able to run the SDK tests on all targets (and ignoring the unsupported methods and resources) 
- [ ] Automate the compatibility matrix process
- [ ] Automate regression control and detection
- [ ] Collecting and listing the left unsupported methods, and resources   
// TBD

### Use Cases

cloud coverage

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
* If this issue is labeled **needs-discussion**, it means the spec has not been finalized yet. Please reach out on the #dev channel in the [Wing Slack](https://t.winglang.io/slack).
