### ISSUE TITLE
Improve the Console

### ISSUE THREAD

**Issue by skyrpex** [winglang/wing#5173]
```[tasklist]
### Tasks
- [x] fix(console): connections to invisible nodes crash the map
- [x] feat(console): stack container nodes
- [x] feat(console): move connections to invisible items higher in the hierarchy https://github.com/winglang/wing/issues/6523
- [ ] https://github.com/winglang/wing/issues/5176
- [ ] https://github.com/winglang/wing/issues/5187
- [ ] perf(console): move elk resolution to the server
- [ ] https://github.com/winglang/wing/issues/5174
- [x] feat(console): add phantom resources to remove connection clutter
- [ ] https://github.com/winglang/wing/issues/5181
- [ ] https://github.com/winglang/wing/issues/2229
- [ ] feat(console): view node in isolation
- [ ] feat(console): show wing code when opening cloud functions
- [ ] feat(console): customize icons for API routes
```
