### ISSUE TITLE
Implementation (SDK/library/sample) (@eng)

### ISSUE THREAD

**Issue by hasanaburayyan** [winglang/wing#5509]
## Task List Summary
- [ ] Publish Wing Cli under `wingcli` (Est. < 1 day) - tracking issue: https://github.com/winglang/wing/issues/5495
- [ ] Add support for quickstart projects (Est. < 1 day) - tracking issue: https://github.com/winglang/wing/issues/5496
- [ ] Support referencing "this" in entrypoint files - tracking issue: https://github.com/winglang/wing/issues/5526
- [ ] Add support for importing existing resources (Est. 2 days) - https://github.com/winglang/wing/issues/5170
- [ ] Create slackbot notifications (Est. 2 days) - https://github.com/winglang/wing/issues/5497
- [ ] Add support for reading Platform inputs via TOML (Est. 2 days)  - https://github.com/winglang/wing/pull/5557
- [ ] Support VPC Endpoints (as well as deploying resources behind vpc) via `tf-aws` target (Est 3 days) - https://github.com/winglang/wing/pull/5557

### Task: Add support for quickstart projects

**Description:**
Adds a new command to the Wing CLI called `new` which will allow users to select from various quickstart projects. After selecting a project the user's current working directory is populated with the starter files of the template chosen.

**Supporting User Story Snippet:**
Ok, now that we have the Wing CLI installed, let's create a new project using the `aws-private-api` quickstart:

```bash
$ mkdir my-api
$ cd my-api
$ wing new private-api-aws
```
> As mentioned above, you can use the --language=typescript option to create a TypeScript version of this project.

**Outstanding questions:**
1. Is supporting both Wing and Typescript p1?

### Task: Publish Wing CLI Under `wingcli`
**Description:**
Users can now install wing cli using `npm i -g wingcli`

**Supporting User Story Snippet:**
Let's start by installing the Wing CLI (you'll need Node.js >= 10.x installed):

```bash
npm i -g wingcli
```

You can check the CLI version like this:

### Task: Add Support For Reading Platform Inputs Through TOML File
**Description:**
Platform specific inputs can be provided via a `wing.toml` file.

**Supporting User Story Snippet:**
Your platform configuration happens inside `wing.toml`:

```toml
[tf-aws]
vpc = "new"
vpc_apigateway = true
vpc_lambda = true
```

This `wing.toml` file sets configuration options for the `tf-aws` platform. The quickstart configures the platform to create a new VPC for this app and put Amazon API Gateways and AWS Lambda functions inside that VPC.

> Built-in Wing platforms such as tf-aws support certain common configuration options (such as private APIs). If you need additional customization, you can always create your own custom platforms and have complete control over how your app is deployed to the cloud.

**Outstanding Questions**
1. (Not a question) -> Need to update Inputs RFC and get it over the finish line https://github.com/winglang/wing/pull/5171

### Task: Create Slackbot Notification App
**Description:**
Whenever a user creates a new quickstart application using `wing new <template>` we should get a notification in slack with statistics on how many times that quickstart application was generated

**Supporting User Story Snippet:**
```
Meanwhile, at the Wing office in Tel-Aviv, a Slack bing ♬ note is heard from all laptops which interrupts a heated office conversation about where to conduct the next Wing offsite. Ainvoner looks at his phone and sees that a Slack message was posted to the #mona-analytics channel. The message reads 🚀 A new "private-api-aws" project was just created! The total number of "private-api-aws" projects created so far is 2,340. He shares this news with the team and everyone start jumping up and down with pure joy.
```

**Outstanding Questions:**
1. What channel (probably a new one)
2. What is the trigger mechanism? (Slack Webhook, Segment Backend Hook, etc..) 

### Task: Support Using VPC Endpoints In `tf-aws` platform
**Description:**
When users choose to have their resources behind a VPC, the default behavior should be no egress and use of VPC Endpoint (Gateways/Interfaces) for interacting with AWS Services.

**Supporting User Story Snippet:**
```
This service needs to be accessed by some internal systems deployed inside the company's private VPC, so Sandy is looking for a way to implement this using an AWS Lambda function and an API Gateway with private endpoint.
```

### Task: Add Support For Importing Existing Resources
**Description:**
Users can import existing resource infrastructure rather than always creating new resources. 

**Supporting User Story Snippet:**

```jsx
bring cloud;
bring aws;

let bucket = () => {
  if app.target == "sim" {
	let bucket = new cloud.Bucket();
	// populate the bucket with data when running in the simulator
	bucket.addObject("updates/billie-001", "status=ok");
	return bucket;
  } else {
    return aws.Bucket.fromBucketName("billie-status-bucket");
  }
}();
```
```[tasklist]
### Tasks
- [ ] https://github.com/winglang/wing/issues/5495
- [ ] https://github.com/winglang/wing/issues/5496
- [ ] https://github.com/winglang/wing/issues/5497
- [ ] https://github.com/winglang/wing/issues/5170
```
