### ISSUE TITLE
User Story: Release Wing Console to the public

### ISSUE THREAD

**Issue by ainvoner** [winglang/wing#937]
# Description

As part of the wing language launch on November 24th we would like to release the first public version of the Wing Console.
In order to have a successful launch for the console the following unimplemented requirements should be met:

# Tasks
 - [x] Console has EULA presented on first use, or there is a checkbox before download that users accept: [Monada Console EULA draft updated Oct30.2022.docx] winglang/console#138 (https://docs.google.com/document/d/1P_5oVRzK8x5ZHSx4XIwUsi8bwkzzNlSp/edit) 
- [x] Application should have an application icon (application and installer) and an installation background winglang/wing#936 
- [x] Enable opening the application without a wx file (open a file explorer for file selection) winglang/wing#938 
- [x] Publish Wing console latest version to a public place so users will be able to download it winglang/wing#935
- [x] Better error handling: winglang/console#164
> - [x] .wx file loading - simple error message for the user
> - [x] simulator errors - simple error message for the user + reloading the simulator when we can
- [x] New Design for the Console center view winglang/wing#953
- [x] Update readme winglang/console#107
